### ISSUE TITLE
Does not work when video was shared from phone

### ISSUE THREAD

**Issue by Ben-Kaniobi** [siku2/script.service.sponsorblock#11]
Great script!
I noticed that it only works when I start a video directly from the YouTube AddOn though.
It does not work when I share the YouTube Video/Link from my phone to Kodi (with Yatse App).

I think when I share the video this way, the YouTube AddOn is still used because I don't think I can do it without having the YouTube AddOn installed. So technically SponsorBlock should still work, right?

**Comment by siku2** [comment]
That's weird, I'm also using Yatse and it works for me (I spent a lot of time making sure that it works).

Do you have the Yatse helper script installed on Kodi? 
Also, can you point me to a video that doesn't work?

**Comment by Ben-Kaniobi** [comment]
I did not have the Yatse helper script installed. I just installed it, but it makes no difference.

[Here](https://youtu.be/FsnaiSu-bmk)'s a video for which I'm getting this behaviour.

**Comment by Ben-Kaniobi** [comment]
Ok, weird, I just tried [another video](https://youtu.be/x9BqK-nq60A) where it works..

**Comment by siku2** [comment]
I was asking about the helper script because that actually makes it worse. I don't recommend having it installed unless you absolutely need it.

Anyway, I'll look into it when I have some time. You could help me out immensely by digging up the logs for when you play the video.

**Comment by Ben-Kaniobi** [comment]
Ok, so I uninstalled the Yatse helper script again.

I enabled Logging and restarted the system. And guess what... It doesn't happen again. The Sponsored part is skipped as it should. It doesn't matter how I start the video, it works now. I cannot reproduce the problem anymore.

So there was probably just something jammed in my system and the reboot helped fixing that..

**Comment by siku2** [comment]
Oh well, that was easy :)
Because of how convoluted the entire Kodi system is, it's easy for something like this to happen.
Don't hesitate to reopen this if it happens again.

**Comment by ape364** [comment]
Hello. First of all, thanks for such a great thing! :)

But I'm facing this issue with this video https://youtu.be/G51PJ5KWAnc
YouTube Vanced on my mobile phone works well.
Here are the [logs](https://gist.github.com/ape364/0f193dbeb024e679e611cc555a8da844)

I see an unhandled exception:

```
2020-11-19 22:44:16.103 T:1268760800   ERROR: Exception in thread Checkpoint Listener:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/osmc/.kodi/addons/script.service.sponsorblock/resources/lib/utils/checkpoint_listener.py", line 148, in __t_event_loop
                                                cp_reached = self.__idle()
                                              File "/home/osmc/.kodi/addons/script.service.sponsorblock/resources/lib/utils/checkpoint_listener.py", line 109, in __idle
                                                return self.__sleep_until(cp)
                                              File "/home/osmc/.kodi/addons/script.service.sponsorblock/resources/lib/utils/checkpoint_listener.py", line 93, in __sleep_until
                                                wait_for = (target_time - self._get_current_time()) / self._playback_speed
                                              File "/home/osmc/.kodi/addons/script.service.sponsorblock/resources/lib/utils/checkpoint_listener.py", line 86, in _get_current_time
                                                return self.getTime()
                                            RuntimeError: XBMC is not playing any media file
```

probably it occurs cuz the ad starts from the very beginning of the video

**Comment by siku2** [comment]
> Hello. First of all, thanks for such a great thing! :)
> 
> But I'm facing this issue with this video https://youtu.be/G51PJ5KWAnc
> YouTube Vanced on my mobile phone works well.
> Here are the [logs](https://gist.github.com/ape364/0f193dbeb024e679e611cc555a8da844)
> 
> I see an unhandled exception:
> 
> ```
> 2020-11-19 22:44:16.103 T:1268760800   ERROR: Exception in thread Checkpoint Listener:
>                                             Traceback (most recent call last):
>                                               File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>                                                 self.run()
>                                               File "/usr/lib/python2.7/threading.py", line 754, in run
>                                                 self.__target(*self.__args, **self.__kwargs)
>                                               File "/home/osmc/.kodi/addons/script.service.sponsorblock/resources/lib/utils/checkpoint_listener.py", line 148, in __t_event_loop
>                                                 cp_reached = self.__idle()
>                                               File "/home/osmc/.kodi/addons/script.service.sponsorblock/resources/lib/utils/checkpoint_listener.py", line 109, in __idle
>                                                 return self.__sleep_until(cp)
>                                               File "/home/osmc/.kodi/addons/script.service.sponsorblock/resources/lib/utils/checkpoint_listener.py", line 93, in __sleep_until
>                                                 wait_for = (target_time - self._get_current_time()) / self._playback_speed
>                                               File "/home/osmc/.kodi/addons/script.service.sponsorblock/resources/lib/utils/checkpoint_listener.py", line 86, in _get_current_time
>                                                 return self.getTime()
>                                             RuntimeError: XBMC is not playing any media file
> ```
> 
> probably it occurs cuz the ad starts from the very beginning of the video

Hm, I see you're using the latest version... We tried to solve this issue in #14, but it probably wasn't enough.
I'm mostly blaming Kodi for this because this happens *after* Kodi claims that the playback has started (i.e. even though Kodi explicitly gives the go-ahead, it still errors). We tried to get around this by adding a small delay to the entire thing, but it seems like that isn't enough in some cases and adding a bigger delay isn't ideal either because then the segment might already be over.
Could you please open a new issue for this? I would like to fix this because a lot of segments start right at the beginning of a video.
