### ISSUE TITLE
seems to skip beyond end of some videos

### ISSUE THREAD

**Issue by idkidk000** [siku2/script.service.sponsorblock#20]
happens on https://www.youtube.com/watch?v=RSRrj2K8tAk with intro, outro and selfpromo skipping enabled
tagged sections for this video: https://sb.ltn.fi/?videoid=RSRrj2K8tAk
after skipping the outro, the last frame of the video is shown but kodi behaves as if the video is still playing and you need to either skip back a few seconds or press next track to go to the next item in the current playlist
honestly i have no idea whether this is a bug in the sponsorblock or youtube addons but i guess you can work around it by checking the end of the skipped section doesn't extend beyond (or within x ms of) the end of the video
kodi debug log: [kodi.old.log](https://github.com/siku2/script.service.sponsorblock/files/5836447/kodi.old.log)
thanks

**Comment by siku2** [comment]
Just released a new version which solves an issue related to this.
Let me know if this has been fixed.

**Comment by idkidk000** [comment]
perfect - that's fixed it!
thanks
