### ISSUE TITLE
Please support Kodi 19.x "Matrix"

### ISSUE THREAD

**Issue by SubZero5** [siku2/script.service.sponsorblock#21]
Please support Kodi 19.x "Matrix"
Ref: https://kodi.tv/article/kodi-19x-matrix-release-candidate

**Comment by siku2** [comment]
Oh absolutely, that would be great. Can't wait to finally use Python 3...
It'll take some time to setup a working test environment but I generally don't expect there to be many issues to fix so this should be fairly straightforward.

**Comment by SubZero5** [comment]
Will happily wait. ;)

**Comment by siku2** [comment]
Looks like the addon itself is already compatible with Python 3. The only problem here is Kodi, because the addon metadata requests Python version 2 instead of 3.
Looks like the only way around this is to have a separate repository for Matrix.

**Comment by teeedubb** [comment]
Great - thanks!
I'll install it over the weekend

**Comment by matejdro** [comment]
I installed it couple of days ago and I must report it works great so far.

**Comment by siku2** [comment]
Cool, closing this then.
