### ISSUE TITLE
Kodi complains "Can't find a next item to play" after playing Youtube video

### ISSUE THREAD

**Issue by matejdro** [siku2/script.service.sponsorblock#22]
I've noticed a mildly annoying issue with the plugin:

After finishing playback of every Youtube video (from what I can tell it happens regardless if there were skips or not), an error message will popup:

![image](https://user-images.githubusercontent.com/507922/111206138-499e5a00-85c8-11eb-8666-d47ae3a18e7f.png)

This is happening with Kodi 19 and was also happening with Kodi 18.X.

**Comment by matejdro** [comment]
Here are logs of this occurring: [kodi2.txt](https://github.com/siku2/script.service.sponsorblock/files/6177820/kodi2.txt). It occurs at 16:59.

This line seems relevant:

> [script.service.sponsorblock] player_listener: segment ends after end of video, **skipping to next video**

But since there is no next video in the playlist, Kodi throws an error.

**Comment by siku2** [comment]
Yeah, that's totally on me. The code doesn't check for an empty playlist because I assumed that Kodi would handle it gracefully.

Should be easy to fix.

**Comment by siku2** [comment]
Fixed in v0.3.1
