### ISSUE TITLE
Support for plugin.video.invidious

### ISSUE THREAD

**Issue by denizonm** [siku2/script.service.sponsorblock#27]
I like the privacy of invidious. It would be great if it had sponsorblock.

**Comment by SethFalco** [comment]
It's unclear which `plugin.video.invidious` this is referring too as there were multiple plugins with the same ID.

The one in the official Kodi repositories as no longer maintained, and had the GitHub repo archived, however.

I think it'd make the most sense to support [lekma/plugin.video.invidious](https://github.com/lekma/plugin.video.invidious).

**Comment by neo-neo1** [comment]
Thank you @siku2
