### ISSUE TITLE
Not Recongizing Stopped Videos

### ISSUE THREAD

**Issue by neo-neo1** [siku2/script.service.sponsorblock#29]
**Problem:**
if I don't press stop on a playing YouTube video and navigate to another Kodi Addon such as `The Crew` and open an IPTV stream SponsorBlock will treat the new IPTV video as previous YouTube video and attempt to skip segments. Same Problem applies when not pressing stop on a playing YouTube video and navigating to a locally stored (or from an NFS folder) video on Kodi and opening it.

**Comment by ryanwalder** [comment]
I've been having a similar issue with on the fly playlists. I've not had the time to fully explore the issue but it's something like:

1. Play local file (Hit enter on local file entry)
2. Add other local files to on the fly playlist (hit `q` on file entry)
3. Add youtube video to on the fly playlist (hit `q` on youtube video entry)
4. [Optional] Add other files/videos to on the fly playlist if wanted

All videos inherit the sponsorblock for the youtube video when played and skip where the youtube video would skip, both in the playlist before and after the youtube video.

Note: I've only tested with local files and a single youtube video.

**Comment by neo-neo1** [comment]
> I've been having a similar issue with on the fly playlists. I've not had the time to fully explore the issue but it's something like:
> 
> 1. Play local file (Hit enter on local file entry)
> 2. Add other local files to on the fly playlist (hit `q` on file entry to enqueue the video(s))
> 3. Add youtube video to on the fly playlist (hit `q` on youtube video)
> 4. [Optional] Add other files/videos to on the fly playlist if wanted
> 
> All videos inherit the sponsorblock for the youtube video when played and skip where the youtube video would skip, both in the playlist before and after the youtube video.
> 
> Note: I've only tested with local files and a single youtube video.

I can definitely confirm I’ve also  experienced similar issues with playlists. Other videos Inheriting the previous video’s SponsorBlock has occurred multiple times to me
