### ISSUE TITLE
v0.5.0 Release

### ISSUE THREAD

**Issue by SethFalco** [siku2/script.service.sponsorblock#51]
Hey hey! 

Any chance we could see a v0.5.0 release soon? I'd really like to document SponsorBlock support in the `lekma/plugin.video.invidious` repo, but I was waiting for it to be available via your repo first. ^-^'

**Comment by siku2** [comment]
I tried to get the release pipeline running again. Let me know if it worked :)

**Comment by SethFalco** [comment]
Perfect, thank you!
Just installed it, and it works well. ^-^

I did notice a bug in one of the PRs I submitted, and will resolve that in a PR. But there's no rush to get it merged.

Under API, I added support for the segment endpoint that gets multiple videos for extra privacy. I accidentally used the same i18n strings as Minimum duration for it though, when it should really have new strings.

Sorry about that! I'll put a PR through in a sec.
